### ISSUE TITLE
运行docker-compose up -d报错

### ISSUE THREAD

**Issue by etoup** [nivin-studio/gonivinck#3]
电脑系统：mac
Shell工具：iTerm2
报错信息：
➜ docker-compose up -d
[+] Building 51.1s (6/10)
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/golang:1.17                                                                                                                                        15.3s
 => [1/7] FROM docker.io/library/golang:1.17@sha256:c72fa9afc50b3303e8044cf28fb358b48032a548e1825819420fd40155a131cb                                                                                   0.0s
 => CACHED [2/7] RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list &&     s  0.0s
 => ERROR [3/7] RUN GOPROXY=https://goproxy.cn/,direct go install github.com/tal-tech/go-zero/tools/goctl@cli                                                                                         35.8s
------
 > [3/7] RUN GOPROXY=https://goproxy.cn/,direct go install github.com/tal-tech/go-zero/tools/goctl@cli:
#6 0.594 go: downloading github.com/tal-tech/go-zero/tools/goctl v1.2.5-0.20211230073016-b98d46bfd629
#6 1.031 go: downloading github.com/tal-tech/go-zero v1.2.5-0.20211230073016-b98d46bfd629
#6 1.441 go: downloading github.com/tal-tech/go-zero v1.2.5-0.20211230062155-e4ab51857606
#6 1.441 go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
#6 1.449 go: downloading github.com/urfave/cli v1.22.5
#6 1.787 go: downloading github.com/iancoleman/strcase v0.2.0
#6 1.793 go: downloading github.com/go-sql-driver/mysql v1.6.0
#6 1.950 go: downloading go.opentelemetry.io/otel/trace v1.1.0
#6 2.017 go: downloading github.com/fatih/structtag v1.2.0
#6 2.082 go: downloading github.com/zeromicro/antlr v0.0.1
#6 2.124 go: downloading github.com/lib/pq v1.10.3
#6 2.323 go: downloading github.com/emicklei/proto v1.9.1
#6 2.338 go: downloading go.uber.org/automaxprocs v1.4.0
#6 2.344 go: downloading go.opentelemetry.io/otel v1.1.0
#6 2.459 go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
#6 2.506 go: downloading gopkg.in/yaml.v2 v2.4.0
#6 2.507 go: downloading github.com/zeromicro/ddl-parser v0.0.0-20210712021150-63520aca7348
#6 2.528 go: downloading github.com/spaolacci/murmur3 v1.1.0
#6 2.719 go: downloading github.com/russross/blackfriday/v2 v2.0.1
#6 2.830 go: downloading github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210521184019-c5ad59b459ec
#6 2.962 go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
#6 34.81 go build github.com/zeromicro/ddl-parser/gen: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c GOPROXY=https://goproxy.cn/,direct go install github.com/tal-tech/go-zero/tools/goctl@cli]: exit code: 1

**Comment by nivin-studio** [comment]
给docker的内存调大一些

**Comment by etoup** [comment]
好的，可以了，谢谢

**Comment by Awadabang** [comment]
> 给docker的内存调大一些
能说一下具体怎么调的嘛。。。我搞了半天都不行

**Comment by nivin-studio** [comment]
> > 给docker的内存调大一些
> > 能说一下具体怎么调的嘛。。。我搞了半天都不行

百度下，docker desktop 的话可以直接在软件上调的。

**Comment by Awadabang** [comment]
> > > 给docker的内存调大一些
> > > 能说一下具体怎么调的嘛。。。我搞了半天都不行
> 
> 百度下，docker desktop 的话可以直接在软件上调的。

 可以了，谢谢！
